//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foodwastagemangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event_Creator
    {
        public int Ev_Id { get; set; }
        public string Ev_Name { get; set; }
        public Nullable<int> Total_Members { get; set; }
        public string Venue { get; set; }
        public string DressCode { get; set; }
        public string Event_Organizer_Name { get; set; }
        public string Event_Organizer_Email { get; set; }
    }
}
