//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foodwastagemangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_Selection
    {
        public int S_Id { get; set; }
        public string Event_Name { get; set; }
        public string Cat_Name { get; set; }
        public string Member_Name { get; set; }
        public string Event_Organizer_Name { get; set; }
    }
}
